### ISSUE TITLE
Unable to compile shared object file on Ubuntu Linux

### ISSUE THREAD

**Issue by mdnunez** [mailchand/CHaRTr#1]
Hello Chandramouli, 

I am having trouble compiling the shared object file on Ubuntu Linux. Running the command `R CMD SHLIB chartr-ModelSpec.c` in the Linux terminal within the CHaRTr main folder results in error `make: Nothing to be done for 'all'.`

Am I missing a makefile?

Thank you,

Michael D. Nunez

**Comment by mdnunez** [comment]
I fixed the problem by removing the .o and .so files. Perhaps all the .o and .so files should be removed from this repository?

**Comment by mailchand** [comment]
Yep! That is right. Sorry for that. We will update it to do so :).
